name = "banana-lean"
version = "0.1.0"
defaultTargets = ["BANANA"]

[[require]]
name = "successor-tree-lean"
git = "https://github.com/janhubicka/lean-successors"
rev = "f073735fb28c998e419128c16d28d212675f8600"

[[lean_lib]]
name = "BANANA"
