name = "banana-lean"
version = "0.1.0"
defaultTargets = ["BANANA"]

[[require]]
name = "successor-tree-lean"
git = "https://github.com/janhubicka/lean-successors"
rev = "d9be105f73ca5a0f3f411b87d4c2419d0eb94753"

[[lean_lib]]
name = "BANANA"
