import BANANA.NonPrecompact.BananaFiniteSupportBlocks

/-!
# Local finiteness of the explicit countable BANANA structure

For a finite set of vectors, the union of their coordinate supports
is finite. The span of the vectors lies entirely inside that finite
coordinate block; because the coefficient field is F₂ and the
coordinate block is finite, this span is finite as a set.

This proves the algebraic local-finiteness ingredient of the
circulation Fraïssé-limit argument. It does not yet prove
ultrahomogeneity or the age of the countable structure.
-/

namespace SuccessorTree.NonPrecompact

/-- A submodule generated by finitely many vectors is contained in
the finite block on the union of their coordinate supports. -/
theorem bananaLimit_span_le_common_block
    (xs : Finset BananaLimitVector) :
    Submodule.span F2 (xs : Set BananaLimitVector) ≤
      bananaLimitBlock (bananaLimitCommonSupport xs ∅) := by
  apply Submodule.span_le.mpr
  intro x hx
  exact bananaLimit_left_mem_common_block xs ∅ x hx

/-- The submodule generated by any finite set is a finite type,
since it embeds in a finite supported coordinate block. -/
noncomputable def bananaLimitFiniteSpanFintype
    (xs : Finset BananaLimitVector) :
    Fintype (Submodule.span F2 (xs : Set BananaLimitVector)) := by
  classical
  let S := bananaLimitCommonSupport xs ∅
  let toBlock :
      (Submodule.span F2 (xs : Set BananaLimitVector)) →
        bananaLimitBlock S :=
    fun x => ⟨x.1, (bananaLimit_span_le_common_block xs) x.property⟩
  have hinj : Function.Injective toBlock := by
    intro x y h
    exact Subtype.val_injective
      (congrArg (fun z : bananaLimitBlock S => (z : BananaLimitVector)) h)
  exact Fintype.ofInjective toBlock hinj

/-- Every finitely generated linear subspace of the countable
finite-support BANANA vector space has finitely many elements. -/
theorem bananaLimit_finitely_generated_span_finite
    (xs : Finset BananaLimitVector) :
    Finite (Submodule.span F2 (xs : Set BananaLimitVector)) := by
  classical
  letI := bananaLimitFiniteSpanFintype xs
  infer_instance

end SuccessorTree.NonPrecompact
